### ISSUE TITLE
Dark mode shouldn't be applied for pagination

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#1016]
Pagination is displayed in dark mode even though we don't have that on Laravel.io

I think this recently got implemented in Laravel so we should probably publish the view and stripe dark mode for now. Or is there a simple toggle in Tailwind we can use for this to always strip dark mode classes?

<img width="1292" alt="Screenshot 2024-01-31 at 20 13 34" src="https://github.com/laravelio/laravel.io/assets/594614/dbeda948-11c1-44e9-b631-3eda870b3874">

**Comment by digitlimit** [comment]
@driesvints I am looking into this.

**Comment by digitlimit** [comment]
@driesvints It's a quick fix according to [](https://tailwindcss.com/docs/dark-mode) 
Please review my PR
