### ISSUE TITLE
Adjust headers for users and articles

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#1122]
Make them not page wide but a rectangle image above the page.

**Comment by tauseefsshah** [comment]
> Not page wide but a rectangle
 
@driesvints Do you mean something like this for articles?

![image](https://github.com/user-attachments/assets/348dc826-aa10-4354-bba0-b760413e671c)

**Comment by tauseefsshah** [comment]
@driesvints How about this? 

![image](https://github.com/user-attachments/assets/5b1d104e-e49d-4b55-8055-f7ebcf1ab700)

**Comment by driesvints** [comment]
looks good! Can we maybe move the text back into the image like we have now?

**Comment by tauseefsshah** [comment]
![image](https://github.com/user-attachments/assets/33592793-71c9-4d71-8ad1-b976c34d6cfb)

![image](https://github.com/user-attachments/assets/a98adde8-c40b-4876-9458-ab78c15b34f0)

**Comment by driesvints** [comment]
Beautiful! Thank you for this 😄

**Comment by tauseefsshah** [comment]
You're welcome! This is how the `users.profile` view looks with boxed header
![image](https://github.com/user-attachments/assets/8bf3d021-d2f2-4eae-b037-a00a7f687a95)

@driesvints Should I keep it page-wide (existing) or boxed (image above)?

**Comment by driesvints** [comment]
Boxed, thanks!

**Comment by tauseefsshah** [comment]
PR for this - https://github.com/laravelio/laravel.io/pull/1140
