### ISSUE TITLE
Open external links in new tab and add utm parameters + Rename twitter to X

### ISSUE THREAD

**Issue by tauseefsshah** [laravelio/laravel.io#1155]
This is not an issue per say but an enhancement that I would like to contribute and before working on a PR wanted feedback from the maintainers.

External links when clicked upon redirect the user away from the site. It would be nice to open these links in new tab and add utm source parameters.
Example: **Pastebin, Chat, Community and Social links** in header, footer, user profile etc

Using X instead of twitter. Twitter word is being used in profile, socials etc.

@driesvints Please let me know what you think

**Comment by driesvints** [comment]
Heya, in general I'm not a fan of adding `target="_blank"` to links as I think it should be a user choice to open these in a new tab. 

What would the benefit for us be to add the utm source params?

Afaik we already use X everywhere?

**Comment by tauseefsshah** [comment]
> Heya, in general I'm not a fan of adding target="_blank" to links as I think it should be a user choice to open these in a new tab.

Makes sense 👍

>  What would the benefit for us be to add the utm_source params?

For social and chat links no benefit as such but for community links and paste bin link it can be helpful for analytics 

> Afaik we already use X everywhere?

Not everywhere, here are some screenshots:
![image](https://github.com/user-attachments/assets/d51e6cd7-d0e7-4fed-aeb5-63886c383ab4)
![image](https://github.com/user-attachments/assets/572b71b2-8153-4f6e-895a-853add0c294c)
![image](https://github.com/user-attachments/assets/32e018ed-1065-471f-b901-fa214f9e0286)

**Comment by driesvints** [comment]
Maybe change the X Twitter naming to "X (Twitter)" and the direct links to `x.com` indeed 👍

**Comment by tauseefsshah** [comment]
Hi @driesvints 
I have sent a PR #1170 for this.

Also I noticed that form labels display the `name` attribute in the slot rather than what's in the slot.
![Screenshot 2024-11-02 at 12 08 30](https://github.com/user-attachments/assets/6d2d53ca-2446-45ce-8166-8d91358ec951)
![image](https://github.com/user-attachments/assets/153af38e-cb97-4f25-bd5f-2a0bde3300e9)
The label should be `X (Twitter) handle` rather than `Twitter`. Is it intentional or it's a bug?

**Comment by driesvints** [comment]
I fixed the label bug in Blade UI Kit itself.
