### ISSUE TITLE
Add option to delete all threads and replies by a user

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#1156]
Add an option in the admin panel underneath users to delete all threads from a user. This is useful to delete threads in bulk while also banning them after they post spam en masse.

**Comment by tvbeek** [comment]
I was already thinking about this feature because it would be very useful 👍

**Comment by driesvints** [comment]
Was thinking about also adding it as an option when banning users to do it all in one go.

**Comment by franbarbalopez** [comment]
Opened a PR doing both things, hope it helps!

**Comment by iam-subho** [comment]
Please confirm if this feature has already been implemented; otherwise, I will proceed to work on it.
