### ISSUE TITLE
IRC Logs for #laravel-dev

### ISSUE THREAD

**Issue by barryvdh** [LaravelIO/laravel.io#173]
Are there plans to log `#laravel-dev` also? Since the new Contributing Guide suggests discussing development here (http://laravel.com/docs/contributions#core-development-discussion)

**Comment by cgrossde** [comment]
Any update on this?

**Comment by driesvints** [comment]
I did some research a couple of weeks ago to find out who's managing the logs atm. I think @JesseObrien manages the #laravel and #laravel-offtopic ones.

I don't really have the time atm anymore to manage these things anymore so I think it's best that if you want this to happen that you contact Jesse or the channel owner (Taylor) to set it up.
