### ISSUE TITLE
Retrieve posts by id via API

### ISSUE THREAD

**Issue by mcraz** [laravelio/laravel.io#201]
The current api displays the recent posts. 

It would be helpful if we could retrive post by id, or even better pass an array of id like we do for the tags and only receive those posts.

**Comment by joshhornby** [comment]
@driesvints I'd be happy to help with the work on the API. I have some ideas and am keen to help build it.

**Comment by pushpak1300** [comment]
@driesvints can I work on this?

**Comment by driesvints** [comment]
I think for now I'm going to hold off on this.
