### ISSUE TITLE
Latest reply user profile link is broken on threads

### ISSUE THREAD

**Issue by awsp** [laravelio/laravel.io#219]
On forum page, the little description under each thread, something like this
```
posted by [OriginalAuthor] - latest reply X hours ago by [LastReplyAuthor] <= the link is broken
```

Attached a screenshot. 
![ss](https://cloud.githubusercontent.com/assets/2015218/8120229/ae7cf94c-1038-11e5-8345-6e5fe74c1066.jpg)

**Comment by driesvints** [comment]
Should be fixed now. Thanks for reporting!
