### ISSUE TITLE
Session issue in L4.0.9

### ISSUE THREAD

**Issue by sanjay-russmediatech** [laravelio/laravel.io#221]
Hi there,

I have an application running on L4.0.9 which servers the API for android and iOS App. Last few days I got a very strange issue I can't get my session value in filters class.

When I login I set the session Session::put('api_logged', true) from action class. After login I called an API called my_items after login but I can't get the value of api_logged in filter class Session::get('api_logged')

Regards,

**Comment by driesvints** [comment]
Hey there @sanjay-russmediatech, please use the forums to ask this. This issue tracker is for bugs with the website.

http://laravel.io/forum

**Comment by sanjay-russmediatech** [comment]
Sure. And thanks for let me know this.

Regards,
