### ISSUE TITLE
irclogs.laravel.io does not work

### ISSUE THREAD

**Issue by rajlaksh** [LaravelIO/laravel.io#222]
**Server not found**

**Firefox can't find the server at irclogs.laravel.io**

**Comment by driesvints** [comment]
I recently transferred the DNS for Laravel.IO and I think this record didn't came along. 

Anyhow, I don't have any intention anymore to do this through Laravel.IO. I also have no idea who hosts the IRC logs. You'll have to ask around on IRC to see who hosts the logs to see if they can set up a domain for it.

**Comment by rajlaksh** [comment]
okay. Thanks for fast reply :+1:

**Comment by rajlaksh** [comment]
@driesvints  can you please do this 

irclogs.laravel.io 
@taylorotwell : the DNS entry should point to 94.23.2.137, could you restore it?

**Comment by driesvints** [comment]
I'll try to setup the DNS record later. 

Taylor doesn't have anything to do with this btw.

**Comment by rajlaksh** [comment]
thanks.

**Comment by driesvints** [comment]
@rajlaksh when I go to that IP I get to see the following: 

![screen shot 2015-07-24 at 13 02 47](https://cloud.githubusercontent.com/assets/594614/8873183/5797b0d4-3204-11e5-95ea-76670b8a1ca7.png)

Are you sure this is the correct IP address?

**Comment by rajlaksh** [comment]
Yes, IP is correct.

That IP i got from Glose.

**Comment by driesvints** [comment]
Ok. Should be back up now: http://irclogs.laravel.io/

**Comment by rajlaksh** [comment]
Thanks. Please keep this DNS safe :)
