### ISSUE TITLE
Titles on posts are wrong, therefore all google search results are wrong

### ISSUE THREAD

**Issue by ShawnMcCool** [laravelio/laravel.io#225]
http://laravel.io/forum/05-21-2014-how-to-disable-remember-token

This should have a title like: [SOLVED] How to disable remember token? - Laravel Community Portal

Or something like that. But, it's just a single title for everything. Therefore searching google is less effective.

**Comment by driesvints** [comment]
@ShawnMcCool I'll have a look at it later this evening

**Comment by driesvints** [comment]
Fixed! Thanks for reporting :)
