### ISSUE TITLE
Rout not found!

### ISSUE THREAD

**Issue by ahkmunna** [laravelio/laravel.io#226]
the installation was fine. when i tried to visit the url(http://laravelio.dev/forum) I got a 404

**Comment by driesvints** [comment]
Hey @ahkmunna. Can you please post a screenshots/stacktrace of the issue? Did you ran through all of the installation steps? https://github.com/laravelio/laravel.io#installation

**Comment by driesvints** [comment]
Are you sure you've set up your `/etc/hosts` file correctly? You seem to be using a different url than the one from the installation steps.

**Comment by driesvints** [comment]
Gonna close this now. Feel free to respond whenever you can.
