### ISSUE TITLE
How to make any user as admin of the forum? 

### ISSUE THREAD

**Issue by evivz** [laravelio/laravel.io#230]
Hello,

I am stuck on making a registered user admin/moderator. Can you help me out with the same.

Thanks.

**Comment by gamefanpage** [comment]
Hi
for the first user Admin you have to do it by Hand on your database

-- ----------------------------
-- Records of role_user
-- ----------------------------
INSERT INTO `role_user` VALUES ('1', '1', '1');
INSERT INTO `role_user` VALUES ('2', '1', '2');

then from admin panel you can set other

**Comment by driesvints** [comment]
The suggestion from above should help you get further :)
