### ISSUE TITLE
Error Create Post category_slug

### ISSUE THREAD

**Issue by FradaL** [laravelio/laravel.io#233]
I followed the installation instructions and I had no problem, I created a user and assigned the roles manually, when I want to create a new topic I get this error:

![Error](http://image.prntscr.com/image/25e788b726804f938f3ea53bab804fbb.png)

I have reviewed the code but I do not understand why that field exists in db if it is not used in the controller.

What could be the problem?

**Comment by FradaL** [comment]
This has worked for me, I do not know if it's the right thing, I'm intrigued to know what category_slug works if there is no category for slug or yes?

I used null the fields category_slug, most_recent_reply_id, reply_count

```  
    public function up()
    {
        Schema::create('forum_threads', function(Blueprint $table) {
            $table->increments('id');
            $table->integer('author_id');
            $table->string('subject');
            $table->text('body');
            $table->string('slug');
            $table->string('category_slug')->nullable();
            $table->integer('laravel_version');
            $table->integer('most_recent_reply_id')->nullable();
            $table->integer('reply_count')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }
```

**Comment by driesvints** [comment]
I think it's indeed because the field needs to be nullable so that's a good fix 👍 

I'm not going to spend too much time on this because this column will go away in the next version.
