### ISSUE TITLE
Use Livewire to edit replies inline

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#266]
It would be nice if we could leverage Livewire to edit replies inline. Endpoints should be checked properly for permissions.

When a reply is edited, it's replaced with the wysiwyg box and when saved the normal reply is shown.

**Comment by LucasLeandro1204** [comment]
Why not use normal web routes for this? @driesvints

**Comment by driesvints** [comment]
@LucasLeandro1204 because of the page refreshes. If we can leverage Vue.js we can offer a much more intuitive experience for our users.

**Comment by bivinvinod** [comment]
@driesvints i think what he meant was why not use the normal web route for making the ajax calls instead of using Laravel Passport.

**Comment by BobbyBorisov** [comment]
i have been wondering the same. what will be the workflow with Laravel Passport. User will login with default web route and LoginController will issue token with certain scope and then it will be returned to the front-end and saved in localstorage for next vuejs requests. The other way is to login with api routes and issue personal access token, i don't know what will happen to non api routes. Probably using cookie. What do you think guys the workflow should be with Laravel Passport?

**Comment by driesvints** [comment]
@BobbyBorisov I haven't used it yet but from what I understand is that Laravel Passport will issue a JWT token that's being bound to the DOM even if you logged in with the current login form. That JWT token can then be used to call API routes which are protected by authentication. I'm going to try to look at setting this up soon.

**Comment by driesvints** [comment]
Updated issue to use Livewire instead.

**Comment by driesvints** [comment]
Updated the issue to focus only on editing replies. Creating replies can still be a page refresh.
