### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#362]
There's already a wip for this at #290. We can make use of the DB implementation to save notifications. Couple this to events and start with the reply notifications.

**Comment by taftse** [comment]
@driesvints Did anything ever happen with this and did you ever get a chance to review the pull requests ?

**Comment by driesvints** [comment]
@taftse no sorry. I just don't have the time atm to spend much work on laravel.io or reviewing the prs.

**Comment by ryangjchandler** [comment]
@joedixon has implemented this, correct?

**Comment by driesvints** [comment]
Not entirely. That was just the first phase. Second phase is realtime notifications with websockets.

**Comment by ryangjchandler** [comment]
> Not entirely. That was just the first phase. Second phase is realtime notifications with websockets.

Ah I see. Any reason why you're choosing to go with websockets over polling with Livewire?

**Comment by driesvints** [comment]
We haven't exactly decided that yet.
