### ISSUE TITLE
Implement Algolia

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#411]
Would be cool if we could leverage Algolia to search for threads, replies and users. 

I think we qualify for an open source plan since the source code is open source.

Algolia requires us to implement a "search by Algolia" logo in the search results: https://www.algolia.com/press/?section=brand-guidelines

**Comment by taftse** [comment]
I have a bit of time tomorrow and might have a look to see how easy it is to implement this with Laravel Scout

**Comment by driesvints** [comment]
@taftse might want to hold of until the redesign by @joedixon is done.

**Comment by taftse** [comment]
@driesvints OK will hold off till the redesign is finished. 
Is there anything else you want me to have a look at in the meantime?

**Comment by driesvints** [comment]
@taftse there's also the pastebin which could use some love: https://github.com/laravelio/pastebin

Thanks for helping out :)

**Comment by driesvints** [comment]
We've soft launched this. Still need to fix a few bugs in the next couple of days.
