### ISSUE TITLE
Jump to solution

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#413]
As a user, I should have an easy way to get to the accepted reply so that I can quickly find the most likely solution to my issue.

**Comment by driesvints** [comment]
What I thought we could do is something like Laracasts and show the accepted reply on top of the other ones.

**Comment by taftse** [comment]
The only thing I find with that type of layout is that you sometimes loose the context I would be more for the have a  "go to accepted solution" link

**Comment by ryangjchandler** [comment]
> The only thing I find with that type of layout is that you sometimes loose the context I would be more for the have a "go to accepted solution" link

Agree with you. I prefer to see the progression of the replies and how the final answer / solution was reached.
