### ISSUE TITLE
Add additional tags - Improvement

### ISSUE THREAD

**Issue by taftse** [laravelio/laravel.io#435]
I would like to suggest we explore adding additional tags for items such as Nova,Vapor,Telescope,Passport,Flare  and maybe some generics such as JavaScript, API just to name a few

**Comment by joedixon** [comment]
I think we’ll want to think about this, particularly given that articles can have tags.

I’ll try to have first pass at this soon.

**Comment by driesvints** [comment]
I added a bunch more tags just now.
