### ISSUE TITLE
Solution button on thread breaks tags

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#495]
Caused by https://github.com/laravelio/laravel.io/pull/492

<img width="423" alt="Screenshot 2020-03-11 at 19 45 52" src="https://user-images.githubusercontent.com/594614/76452285-2ba88300-63d1-11ea-9090-a243f3677ee5.png">

**Comment by ryangjchandler** [comment]
I'm on it.

**Comment by ryangjchandler** [comment]
Sorry for causing that problem guys. I've made a PR ^^^ to resolve it. Completely forgot tags existed since none of my test threads had any. Will be sure to test better next time. Sorry again <3

**Comment by driesvints** [comment]
@ryangjchandler no worries, I missed it myself as well :)

Maybe it's best that we also seed some tags.
