### ISSUE TITLE
Build a new API

### ISSUE THREAD

**Issue by ryangjchandler** [laravelio/laravel.io#497]
I think it would be pretty sweet to have an API for the forum. For example, I might want to show off my replies and thread count on my own personal site, or even share some of my replies that are marked as solutions.

I'd be pretty happy to work on this and I'd definitely enjoy it.

**Comment by driesvints** [comment]
Definitely. Let's first make a list of all the endpoints we need. I don't think we only need GET endpoints for now. I don't think it makes sense to allow data manipulation through an API atm.

Relates to https://github.com/laravelio/laravel.io/issues/201

**Comment by ryangjchandler** [comment]
For sure, I can't see need for data manipulation, just retrieval of data. Might be a nice use case for Airlock maybe...

**Comment by driesvints** [comment]
Don't think we'll need airlock in the portal since we're more focussing on Livewire.

**Comment by driesvints** [comment]
Heya. I'm going to close this one. I don't see a public API for the forum happening any time soon, sorry.
