### ISSUE TITLE
Filter Forum posts

### ISSUE THREAD

**Issue by imrodrigoalves** [laravelio/laravel.io#501]
Hello,

While looking at the forum I sometimes miss a option to filter the posts by the following criteria:

- Answered/Not Answered/With comments/Without comments
- Date

Great work, see you :)

**Comment by ryangjchandler** [comment]
I like the idea of this. Would like to see some filters for solved threads too.

**Comment by driesvints** [comment]
We might be able to tie this into Algolia instantsearch.

**Comment by joshuamabina** [comment]
Hello,

Is there an update on this issue? Would love to take it given some guidance.

Much appreciated.

**Comment by driesvints** [comment]
If there's no response then no there's no update ;-)

I think this is gonna be a hard one given that we'd need to implement it properly UI wise as well. I don't have time atm to think this over properly but suggestions are always welcome.
