### ISSUE TITLE
Community Publishing

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#506]
For a long time now, the Laravel.io forum has been a great and active community resource.

The goal of community publishing is to extend upon the fantastic foundation we have by offering our users a platform on which to publish articles about Laravel and its surrounding community.

You can think of it like medium.com or dev.to but specifically for Laravel.

The writing experience should be simple and intuitive - perhaps using [Wink](https://wink.themsaid.com/) (or at least its text editor) from Mohamed.

Users will be able to choose the title and write the article. Slugs will be generated dynamically. We should offer simple editor options:

* H1-H3
* Lists
* Bold, italic
* Images
* Links
* Code blocks

Articles will be stored in markdown.

Users should be able to like articles in some way. This should probably use the existing thumbs up/down approach which we have for threads and replies.

Much like our forum posts, articles can be assigned tags and will be indexed to Algolia to make them easier for users to find.

Users should have the ability to follow tags and other users so that we can present articles to them which they may find interesting. This can tie in nicely to the existing notification system.

We should have in mind from the outset that articles can be linked together into a series. One thing that grinds my gears is when I can’t find part 4 of a 5 part series so it should be easy to navigate between each part.

**Comment by driesvints** [comment]
Couple of things: we should own the code as much as possible so we can easily make adjustments so I don't think using Wink is the right approach here.

Also, I think we should make use of a single editor so it's probably best to re-use the same one as for the forums. Or replace the forum one. It doesn't makes much sense to me to use multiple editors on the portal. Definitely a focus on Markdown.

> Users should have the ability to follow tags and other users so that we can present articles to them which they may find interesting. This can tie in nicely to the existing notification system.

This can be done in a follow up PR.

> We should have in mind from the outset that articles can be linked together into a series. One thing that grinds my gears is when I can’t find part 4 of a 5 part series so it should be easy to navigate between each part.

Let's do this in a follow up PR as well. Smaller prs so we can launch things quicker 👍 

For the rest this looks perfect. Let's do this! 🙂

**Comment by joedixon** [comment]
> Also, I think we should make use of a single editor so it's probably best to re-use the same one as for the forums. Or replace the forum one. It doesn't makes much sense to me to use multiple editors on the portal. Definitely a focus on Markdown.

OK, I agree, let's go for the current editor to get the feature built.

However, I do have some push back for the longer-term. I agree that we shouldn't use Wink, but I'm not sure the editor should be the same as the forum. I think people expect a different experience when writing an article compared writing a forum post. Think about Medium or Gutenberg for Wordpress (love it or hate it). In my opinion, if we want to entice people to use Laravel.io for the blog post they've been working hard on for days or weeks, we need offer a comparable experience.



> Let's do this in a follow up PR as well. Smaller prs so we can launch things quicker 👍

🚀
