### ISSUE TITLE
Search results overflow

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#508]
When you have a long string of non breaking text in your search result, it overflows the search box.

<img width="644" alt="Screenshot 2020-04-05 at 12 23 24" src="https://user-images.githubusercontent.com/594614/78472363-5ec40500-7738-11ea-9276-4df1ae5375b3.png">

**Comment by joedixon** [comment]
I fixed this in Chrome, but it's broken in Safari 😕

Will take a look
