### ISSUE TITLE
Ads on the site are sketchy

### ISSUE THREAD

**Issue by exxy** [laravelio/laravel.io#511]
Here's a [screenshot ](https://i.imgur.com/znEnL6s.png) of an ad I saw on the Laravel.io site today.

Obviously, the Laravel.io project does not aim to trick or mislead the Laravel community.  Ads like this are characteristic of shady/dubious websites.  It may give new users the wrong impression of the site.

**Comment by driesvints** [comment]
I've blocked the related ad in AdSense and reported it. Thanks for reporting!
