### ISSUE TITLE
Make "tags" filter collapsible on mobile

### ISSUE THREAD

**Issue by ryangjchandler** [laravelio/laravel.io#518]
I've attached a screenshot. On an iPhone XR, the tags list takes up the entire viewport. I think it should be collapsible or collapse by default on mobile devices. 
![60D448BF-CD98-4F17-ADB3-89DC5171FEFD](https://user-images.githubusercontent.com/41837763/80322956-2340c600-8820-11ea-8c4b-b3b2027044bc.png)

**Comment by driesvints** [comment]
Yeah we should definitely take care of that at some point.

**Comment by ryangjchandler** [comment]
@driesvints, I'm happy to throw in a PR to sort it out - maybe use Alpine?

**Comment by driesvints** [comment]
Yeah could be cool. Maybe check with @joedixon?

**Comment by joedixon** [comment]
Hey @ryangjchandler - 

I definitely think this is something we need. It's not a great experience on mobile.

With the [community publishing PR](https://github.com/laravelio/laravel.io/pull/510) I'm working on, I potentially see the need to add more tags so this will only go to compound the issue.

I think it would be a cool starting point to make it collapsible, but at some point, I'd also like to add the ability to search tags and maybe even only present the 5 most used when expanded as it's quite hard to find what you want in a huge list.
