### ISSUE TITLE
Auto link URLs in threads and replies

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#529]
At the moment, when writing a URL into a thread or reply, it is rendered as plain text. Would be cool to automatically make these links.

**Comment by pushpak1300** [comment]
can i work on these?

**Comment by driesvints** [comment]
@pushpak1300 go for it!

**Comment by pushpak1300** [comment]
@driesvints I was following this [thread](https://laracasts.com/discuss/channels/general-discussion/textarea-with-hyperlinks).
What do you think how should I approach this issue?

**Comment by pushpak1300** [comment]
Should I handle this on client-side or server-side?

**Comment by driesvints** [comment]
I think we want to do this client side.

**Comment by pushpak1300** [comment]
```js 
// Find url in html
function findurls(html) {
    var urlRegex = /(https?:\/\/[^\s]+)/g;
    return html.replace(urlRegex, function (url) {
        return '<a target="_blank" rel="noopener" href="' + url + '" >' + url + '</a>';
    })
}

// Url highlight 
window.linkyfy = (element) => {
    element.querySelectorAll('p').forEach((block) => {
        block.innerHTML = findurls(block.innerHTML);
    });
}
```

So I am using this code to convert links after markdown has changed to html but problem is that if any link already present in markdown the function is converting it to anchor link.
it is working fine if no link is present when anchor tag is present.
i.e  Changing this html
``` <p><a href=\"https:\/\/github.com\/alpinejs\/alpine#x-init\">ask<\/a><\/p>\n"```
to
``` <p><a href="<a target=" _blank"="" rel="noopener">ask</a>" &gt;https://github.com/alpinejs/alpine#x-init"&gt;ask</p>```

can you help? @driesvints

**Comment by driesvints** [comment]
@pushpak1300 omg sorry. I meant server side 🤦

**Comment by pushpak1300** [comment]
okay.

**Comment by driesvints** [comment]
What I think we want to do is replace any standalone urls in the rendered markdown content with `<a>` surrounding tags. I'm guessing we aren't the first ones with this problem so I'm suspecting there might be a PHP library on Packagist that can help us out.

**Comment by pushpak1300** [comment]
https://github.com/nahid/linkify check this out @driesvints

**Comment by driesvints** [comment]
Hmm, seems to not be maintained anymore. Think https://github.com/yarri/LinkFinder will serve us better.

**Comment by pushpak1300** [comment]
I will use this package then @driesvints .
