### ISSUE TITLE
Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by NesmaJarour** [laravelio/laravel.io#536]
Hi!
when I write in command --
php artisan db:seed --class=CategoriesTableSeeder
This error appears
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Laravel' for key 'categories_name_unique' (SQL: insert into categories (created_at, is_published, name, slug, updated_at, user_id) values (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1))

at C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
667| // If an exception occurs when attempting to run a query, we'll format the error
668| // message to include the bindings with SQL, which will make this exception a
669| // lot more helpful to the developer instead of just the database's errors.
670| catch (Exception $e) {

671| throw new QueryException(
672| $query, $this->prepareBindings($bindings), $e
673| );
674| }
675|

1 C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Laravel' for key 'categories_name_unique'")

2 C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
PDOStatement::execute()

**Comment by driesvints** [comment]
We don't have a categories seeder so this seems like a custom change you made. Best that you ask this on a support channel like Laracasts or Laravel.io itself.
