### ISSUE TITLE
Auto post articles to Twitter

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#539]

**Comment by driesvints** [comment]
Would be cool if people could fill out their twitter handle in their profile so we could link to that automatically in the tweet. If they haven't filled it out then we'll just post their name. 

Probably also best to set a message in the create article screen or submit article button that they'd best fill out their twitter handle in their profile if they want to be auto linked.

**Comment by joedixon** [comment]
@driesvints what do you think of this solution:

- Create a job which posts the article to Twitter
- Schedule the job to run every minute
- Use a lottery similar to Laravel's session garbage collector which determines if a tweet should be posted
- If the lottery wins, grab the latest published article which hasn't been shared and share it

I like this more than, for instance, running every hour as it feels more random.

**Comment by driesvints** [comment]
Don't we need to first tweet the oldest published article? Also: we'll need to mark the article as tweeted so we don't make the mistake of tweeting twice.
