### ISSUE TITLE
Community Publishing - Issue sorting 

### ISSUE THREAD

**Issue by taftse** [laravelio/laravel.io#545]
I'm looking through the articles and was expecting them to be sorted in most recent first (as the recent button was selected) but they seem to be random 

![image](https://user-images.githubusercontent.com/679269/86610876-d149b880-bfa5-11ea-89c2-b2094bc76833.png)

I had a look at the other two options but don't know what popularity or trending is based on so cant say if they are right or wrong

**Comment by driesvints** [comment]
Hey @taftse that's indeed true but the first one is pinned. I now notice we don't visually indicate this anywhere @joedixon.

**Comment by joedixon** [comment]
Thanks for pointing this out. I'm going to make it more obvious in the results.
