### ISSUE TITLE
Resend verification link doesn't 

### ISSUE THREAD

**Issue by tvbeek** [laravelio/laravel.io#560]
I did need to verify my account to participate in a thread (not a problem)

But if I click here:
![image](https://user-images.githubusercontent.com/2026498/97149722-6d721800-176d-11eb-864a-78d75485691d.png)

I got:
![image](https://user-images.githubusercontent.com/2026498/97153708-3868c400-1773-11eb-9abf-1bc8b52804c0.png)

The button on creating a new thread did function so I could verify my email address  :) 

It looks like the problem is that the first button is a link with a GET request while it should be a POST.

**Comment by driesvints** [comment]
Thanks, we'll try to look into this soon.

**Comment by driesvints** [comment]
Fixed in https://github.com/laravelio/laravel.io/pull/561
