### ISSUE TITLE
Memory limit hit when running tests

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#575]
<img width="680" alt="Screenshot 2020-12-28 at 14 24 59" src="https://user-images.githubusercontent.com/3438564/103220582-81c2c480-4918-11eb-8bf8-4db37363119d.png">

Seems to be caused by the volume of tests in `Tests\Feature\ArticleTest.php` - it may be worth splitting this into smaller files.

**Comment by driesvints** [comment]
We can now make use of parallel testing from Laravel to prevent this.
