### ISSUE TITLE
into forum page error

### ISSUE THREAD

**Issue by SamJheng** [laravelio/laravel.io#578]
i can't go to the forum page
is alway repo error 

`Illuminate\Database\QueryException
SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelio.threads.author_id' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `threads`.*, CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at THEN COALESCE(MAX(replies.created_at), 0) ELSE threads.created_at END AS latest_creation from `threads` left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = threads group by `threads`.`id`) as `aggregate_table`)
http://127.0.0.1:8000/forum`
![image](https://user-images.githubusercontent.com/33681236/103279509-ed845a80-4a08-11eb-8c5c-c17317d459cf.png)

any have idea?

**Comment by joedixon** [comment]
In your `database.php`, try turning off strict mode in the mysql settings:

```php
'mysql' => [
    ...
   'strict' => false,
    ...
],
```

**Comment by SamJheng** [comment]
@joedixon  ok thanks you help! it's work
