### ISSUE TITLE
Decline articles

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#580]
Add the ability to decline articles so they don't appear in the pending list anymore on the admin site. No message needs to be sent out.

**Comment by thinkverse** [comment]
So declining should act as a soft delete almost? Perhaps resetting the `submitted_at` to `null` would work? That would return the article to a draft, giving the user the option to rewrite sections and resubmit for review.

Thoughts?

**Comment by driesvints** [comment]
Not really soft deleting, the articles will still be in a person's list of articles. 

In general we've found that when we decline articles they're usually just not the type of articles we're looking for so a rewrite isn't really applicable.
