### ISSUE TITLE
Add info panel when writing article

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#581]
When writing an article there should be an info panel informing the writer what the rules are for submitting an article. Most of these should conform to our general rules: https://laravel.io/rules

Also inform that article approval is at our discretion and that we don't accept all articles. Inform the writer that when an article isn't approved, no notification is being made. Suggest to cross-post articles on the writer's blog, other channels, etc.

**Comment by pushpak1300** [comment]
I'm on it!
