### ISSUE TITLE
Add SSO with CAS and remove Login using Git

### ISSUE THREAD

**Issue by desyashasyi** [laravelio/laravel.io#585]
Hi, I want to adopt Laravel.io for a discussion portal, however.. it is not for developer, hence most of user are not have github  account. How to revert the authentication using Laratrust: https://laratrust.santigarcor.me and also using SSO Subfission/CAS: https://github.com/subfission/cas

**Comment by driesvints** [comment]
Heya, this is something we probably won't be implementing ourselves, sorry. We require GitHub authentication specifically to combat spam accounts. It's been proven the only effective way to fight that so far. Most developers also probably have a GitHub account. 

If you're adopting the portal for a different use case feel free to fork it and implement your own login system 👍
