### ISSUE TITLE
Add a rich text editor

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#593]
For both forum, articles and replies so people can toggle between what they like. Rich text editor **should not** provide image upload. 

Probably needs a new trait or something and a column on replies, articles, forum to indicate which editor was used to write it. A component could be made to toggle the rendering of the content. Probably re-use a Blade UI Kit richt text editor.

**Comment by ajuchacko91** [comment]
Hi @driesvints, why did you closed this? are you still interested in getting a pr for this?

**Comment by driesvints** [comment]
No not really. Think markdown is enough.
