### ISSUE TITLE
Notifications icon in nav has incorrect hover state

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#598]
We probably missed this during the Tailwind CSS update. Needs to be a color change or fill instead.

![Screenshot 2021-02-13 at 11 51 00](https://user-images.githubusercontent.com/594614/107848207-d00d2380-6df1-11eb-98b3-35cd0806eca3.jpg)

**Comment by pushpak1300** [comment]
@driesvints do you need an outline on a hover state or not?
<br>
![Screenshot from 2021-03-07 12-49-06](https://user-images.githubusercontent.com/31663512/110232413-87094480-7f43-11eb-85dd-3c5ca27e2d65.png)

![Screenshot from 2021-03-07 12-48-07](https://user-images.githubusercontent.com/31663512/110232396-6640ef00-7f43-11eb-934b-d9f6d6e1b82e.png)

**Comment by driesvints** [comment]
Don't think we need an outline at all
