### ISSUE TITLE
laravel.io clone optimization

### ISSUE THREAD

**Issue by dk009dk** [laravelio/laravel.io#600]
Recently I downloaded the code of laravel.io and deploy application on my local server as well as i deploy on heroku but when i open laravel.io it's response time is around 0.5 to 1 second but in my application in local server and heroku both it take 10 to 15 second for loading homepage as well as another pages.

Heroku url is [https://enggxchange.herokuapp.com](https://enggxchange.herokuapp.com) 

What optimization i need ?

After run command npm run dev generated mix file are app.css is 4.17Mb and app.js is 1.12Mb is it normal or any error in my case ?

**Comment by driesvints** [comment]
I'm afraid this issue tracker probably isn't the correct place to ask this. Please try the Laravel.io forums themselves.
