### ISSUE TITLE
Tags don't yet appear on article page

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#616]
If you add tags to an article they should also appear when the article is shown.

**Comment by YunusDev** [comment]
I will work on this

**Comment by YunusDev** [comment]
Hi @driesvints I cant push a branch to the repo. I just worked on this **enhancement**. Is there anything else I need to do before I can contribute. 
Thanks

**Comment by driesvints** [comment]
Hey @YunusDev. We're revamping the article page soon so this issue is no longer invalid. There's still other small issues like https://github.com/laravelio/laravel.io/issues/618 which you can always help out with if you're feeling up to it :)

Thanks!

**Comment by YunusDev** [comment]
Oh okay. Thanks. @driesvints. Will check it out. This actually my first time attempting to contribute to a repo. So I want to know if there is anything I need to do to contribute. Because I was trying to push the branch I created to the repo but I got a 403. Thanks

**Comment by driesvints** [comment]
Hey @YunusDev. Usually you "fork" a repo first. There's a fork button on the repo on the top right. Then you can push to that repository and make a PR to the original repository. If anything's not clear don't hesitate to ask questions 👍

**Comment by YunusDev** [comment]
Oh okay. Thanks. @driesvints. I cloned that's why I got the error.
