### ISSUE TITLE
Refactor jobs to use dispatchSync

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#626]
This refactor has two parts: refactor jobs to never return anything form their handle method (add void return type) and use dispatchSync instead of the deprecated dispatchNow.

**Comment by bensherred** [comment]
Hey @driesvints,

I'd be interested to know your thoughts on how you plan to refactor the controllers that currently use the output from jobs? For example, in the ArticlesController [store](https://github.com/laravelio/laravel.io/blob/main/app/Http/Controllers/Articles/ArticlesController.php#L56) method you get the created article back from the job and then use that to redirect to the user to the newly created article.

However, if the job no longer returns the instance or id, how do you plan to accomplish this?

**Comment by driesvints** [comment]
The way to accomplish this is probably to generate a UUID first, pass that to create the article, then retrieve it after synchronously dispatching the job.

**Comment by bensherred** [comment]
Is there a reason for the handle methods not returning a value? When using `dispatchSync` on non queueable jobs the response from the `handle` method would be returned. The only reason I ask is because if you use the UUID approach, you would then have to execute a second database query to get the value?

**Comment by driesvints** [comment]
Laravel doesn't recommend jobs to return a value anymore and we're actively encouraging people to step away from doing that. See the answer by Taylor here: https://github.com/laravel/framework/issues/37023#issuecomment-822543770

**Comment by driesvints** [comment]
In general, from a command bus approach, it's also never expected that a command execution returns anything

**Comment by bensherred** [comment]
Ah that makes sense. Would it be better to use an "actions" approach instead, rather than jobs for the cases where a value needs to be returned?

**Comment by driesvints** [comment]
Basically if you need a return value it's best that you create a custom class yeah. That could be "actions" or whatever terminology you use for those.

**Comment by bensherred** [comment]
That makes a lot of sense, thanks Dries 😄

**Comment by joelbutcher** [comment]
@driesvints Planning on taking a look into this, which is your preferred approach.. 1) going by your suggestion, generate a UUID to be passed to each job, cache the result of the job and retrieve that from the cache after the job is executed. Or 2) update and move the jobs that return data to "actionable" classes and call those instead?
