### ISSUE TITLE
laravel application installation issue in local host

### ISSUE THREAD

**Issue by fazlur10** [laravelio/laravel.io#683]
when i try to install a laravel application at localhost and run following errors occur, How can i solve these?
Fatal error: Uncaught RuntimeException: A facade root has not been set. in C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:258 Stack trace: #0 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(426): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array) #1 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(403): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #2 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(314): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException)) #3 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(211): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Compone in C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 258

**Comment by driesvints** [comment]
Please post this on the forum instead.
