### ISSUE TITLE
Add heights and widths to all images

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#694]
Google Search Console a good proportion of visits are suffering from Cumulative Layout Shift (CLS). This is when the layout of a page suddenly shifts when something happens such as an image loading.

To prevent this, all images should be loaded with a width and height so the space on the page is already accounted for.

For more information, see how to [optimize cumulative layout shift](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=unknown#images-without-dimensions).

**Comment by driesvints** [comment]
Gonna mark this as an enhancement as there's nothing really broken here.

**Comment by driesvints** [comment]
Gonna close this one for now.
