### ISSUE TITLE
Block users

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#698]
We should allow our users to prevent abuse by blocking other users. This will allow them to not receive mentions from these users anymore. People can still mention others but they won't receive replies from them any longer.

People should be able to maintain a list of blocked users through their settings.

Depends on https://github.com/laravelio/laravel.io/issues/271

**Comment by Gbemiro8** [comment]
Hi @driesvints, by mentions I assume you mean using "@" to mention a user when someone posts a comment/reply.
But after going through the codebase, I did not find a "@" mention functionality implemented, or do you mean blocking notifications if a particular user replies to a thread?
Correct me if I'm wrong & code pointers would be appreciated!

**Comment by driesvints** [comment]
/

**Comment by driesvints** [comment]
Hey @Gbemiro8 this depends on #271 which we're still working on (see the last line in the issue description)
