### ISSUE TITLE
Preview threads & replies

### ISSUE THREAD

**Issue by tvbeek** [laravelio/laravel.io#706]
I think it could be useful to have a preview option option before saving a thread or reply. This can prevent some messages that aren't formatted on the prefered way.

An option is the way that GitLab does, you have 2 tabs. The first is where you write and the second is the preview. If you switch to the second you get a call to the server that returns the preview. (In fact the same technique that livewire used.)

**Comment by tvbeek** [comment]
@joedixon I mean we could use Livewire to let the preview be rendered on the backend on that way it can be totally the same code that renders the content after saving. It prevents the option that there is a different between the preview and the saved rendering.

**Comment by joedixon** [comment]
Thanks @tvbeek, I'm going to start working on this soon as part of reskinning the editor. 

It would be great if you could do me a favour and send a screen shot/recording the the feature on gitlab

**Comment by joedixon** [comment]
That's great thank you.

I only just realised the GitHub has this functionality 🤦‍♂️
