### ISSUE TITLE
outdated link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tvbeek** [laravelio/laravel.io#746]
From: https://github.com/laravelio/laravel.io/blob/main/CONTRIBUTING.md

> Bug fixes should contain regression tests
The link points to: https://laracasts.com/lessons/regression-testing but that isn't working. Does it need to have another URL, the link removed or the whole line removed?

`vendor/bin/phpunit` this should be changed to `vendor/bin/pest` 😃  (I thought it could be one PR)

**Comment by driesvints** [comment]
Fixed, thanks!
