### ISSUE TITLE
Notify us on Telegram when new articles are submitted

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#751]
When a new article is submitted, notify us on Telegram in our Laravel.io group. Use the Telegram notification channel.

**Comment by faissaloux** [comment]
@joedixon are you working on this! because I have already worked on a script for that (A telegram bot that sends messages to telegram channels) that I always work with on my projects.

I'm thinking of making a little package of it and use it on this project. What do you think!

**Comment by driesvints** [comment]
@faissaloux thinj we just need the telegram notification channel for this.

**Comment by faissaloux** [comment]
Ah you talking about this https://github.com/laravel-notification-channels/telegram .. I see, I didn't know about it, okay.

Is there someone working on this!!

**Comment by joedixon** [comment]
Hi @faissaloux - I was planning to pick this up, but will be a little while before I can get around to it so happy if you would like to take it on. Thanks!
