### ISSUE TITLE
Error when sending notification of new article

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#774]
Telegram responded with an error `400 - Bad Request: group chat was upgraded to a supergroup chat`

I think for some reason the group ID has changed since testing.

**Comment by faissaloux** [comment]
Have you upgraded the group to a supergroup!!

**Comment by faissaloux** [comment]
1- Have you upgraded the group to a supergroup!!
2- Have you updated the group ID!

**Comment by driesvints** [comment]
Guess we can close this now. We're receiving notifications fine now.
