### ISSUE TITLE
TypeError: search is not a function

### ISSUE THREAD

**Issue by aleksrutins** [laravelio/laravel.io#784]
When attempting to search through the bar in the top menu, it fails with an error of 'search is not a function'. The thing is, `window.search` is a function, and I can use it through DevTools. One solution that works (on my machine, at least) is to change the `keyup` event on `input#search` here:
<https://github.com/laravelio/laravel.io/blob/d05a9dc5a8c12de9defbc7236cd90cef9dadb62b/resources/views/_partials/_search.blade.php#L11>
to explicitly reference `window.search` instead of just `search`.

**Comment by driesvints** [comment]
Thanks for letting us know. We'll check in on this.

**Comment by aleksrutins** [comment]
Should I create a PR?

**Comment by driesvints** [comment]
Yes, thank you!
