### ISSUE TITLE
Article search broken

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#787]
It seems for some reason, articles aren't showing up any more in the search.

<img width="759" alt="Screenshot 2021-12-21 at 16 47 10" src="https://user-images.githubusercontent.com/594614/146958740-c70a7344-8205-49ee-beab-2a45274c779a.png">
<img width="548" alt="Screenshot 2021-12-21 at 16 47 17" src="https://user-images.githubusercontent.com/594614/146958744-140dfb06-ac12-494a-9b1f-c35add8d32b4.png">

**Comment by driesvints** [comment]
We did merge https://github.com/laravelio/laravel.io/pull/785 which fixed search itself so maybe there's one more fix needed?

**Comment by aleksrutins** [comment]
Hmm, it worked for a moment on my computer:
<img width="720" alt="Screen Shot 2021-12-21 at 10 50 06 AM" src="https://user-images.githubusercontent.com/24496030/146959196-1815eaff-4fd3-450d-b3ba-51e7c75c37de.png">
But now it doesn't.

**Comment by aleksrutins** [comment]
Hmm, the responsive search toggle doesn't seem to work either. It seems to be using as a toggle a variable called `search`, which I don't see in any data bindings &mdash; would that conflict with the `search` function? Maybe that's the actual issue that was happening with #784.
