### ISSUE TITLE
Sorting order?

### ISSUE THREAD

**Issue by aleksrutins** [laravelio/laravel.io#792]
When sorting the list of posts in the forum, the sorting order seems almost completely random. When filtering by recent, a post from seven years ago appears above a post from one month ago:
<img width="931" alt="Screen Shot 2021-12-22 at 12 05 15 PM" src="https://user-images.githubusercontent.com/24496030/147129351-d0e3aeb4-746f-4c51-af67-6bbf224c3e28.png">
Am I misunderstanding how this works? Is this intended? Is this not yet implemented?

**Comment by driesvints** [comment]
The sorting depends on last activity. The given date is the thread's creation date but sorting depends on the last activity. GitHub discussions works similar. It is however, strange that this particularly thread got bumped even though no new reply was added. Maybe a new reply was posted and removed. We should indeed investigate why this happened and how we can prevent that from happening again.
