### ISSUE TITLE
Last updated for thread start is updated if a new reaction is added

### ISSUE THREAD

**Issue by tvbeek** [laravelio/laravel.io#817]
After adding some replies I saw that the Last updated for a thread message is updated to the last added reply.

I suspect it is a side effect of: https://github.com/laravelio/laravel.io/pull/800 because the last_activity_at is now changed and that result in an updated_at change.

**Comment by driesvints** [comment]
Thanks @tvbeek, I agree this needs fixing.

**Comment by joedixon** [comment]
Yeah, I agree. Will get a fix up ASAP.
