### ISSUE TITLE
User mentions does not show user list box in the last version of livewire (v2.10.2)

### ISSUE THREAD

**Issue by rvalenzuelaferrada** [laravelio/laravel.io#826]
File `editor.js` `Line 113` function `showUserListbox()`
when the users public property of the editor is accessed, it always returns zero.
therefore the user list box is never displayed.

I don't know how to solve this conflict.

To reproduce the error, just clone the repo and run `composer update`

**Comment by driesvints** [comment]
Thanks for reporting. We'll look into this.
