### ISSUE TITLE
Add setting to turn off mention notifications

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#827]
Add a new settings section for notifications with a setting to globally turn off/on notifications for subscriptions to threads, including mentions.

**Comment by bad915** [comment]
Hello, I would like to contribute. I'm willing to take this task. How I do it right way ? After reading the contribution guide felt like I have to talk before doing anything.

**Comment by sodu-parisev** [comment]
![image](https://user-images.githubusercontent.com/13131900/215321718-0e105931-3dc1-407f-bde2-1e0806d8c975.png)
I assume should look like this. Also it means `notifications` boolean field will be added to `users` table. The field will server as toggle.

**Comment by driesvints** [comment]
So I think we should maybe look into a `notifications` JSON column that can hold settings for different notification types later on as well. I think we should display it as a list of type of notifications (currently only one) with a checkbox to toggle them on or off (by default on). The `notifications` settings would only contain a setting of a type of notification is turned off.

**Comment by tvbeek** [comment]
Maybe it is an idea to directly split the current situation in 2 notification settings?

One for the new reply notification and another for the mentions? (Now a new reply that mentions you result in 2 notifications so I think it can be useful to manage them separately)

**Comment by driesvints** [comment]
That’s actually a bug and shouldn’t happen. Can you maybe open an issue for that @tvbeek?

**Comment by tvbeek** [comment]
> That’s actually a bug and shouldn’t happen. Can you maybe open an issue for that @tvbeek?

Yes, done in #937

**Comment by sodu-parisev** [comment]
I guess better to have #937 done first ?

**Comment by driesvints** [comment]
They're separate things really.

**Comment by sodu-parisev** [comment]
What I got from conversation above is:

1. We will have `notifications` json field on `users` table
2. The field will store a list of json objects like for example [{"reply":"off"},{"mentions":"off"}] 
3. On the settings page will be shown list of notification types with checkboxes to toggle them on/off  

am I right ?

**Comment by driesvints** [comment]
More like:

```
[{"replies":false},{"mentions":false}]
```

**Comment by sodu-parisev** [comment]
okay, got it, will do

**Comment by sodu-parisev** [comment]
Hey, here I have dome something, please let me know am I going right. This is not finished yet but I think it is mostly done like 90%. [pull request][(url](https://github.com/laravelio/laravel.io/pull/938))

**Comment by dolgeneraldgme** [comment]
Here are the steps:

1.	Go to your GitHub account and log in.
2.	Navigate to the repository for which you want to add the setting to turn off mention notifications.
3.	Click on the "Settings" tab on the right-hand side of the screen.
4.	Scroll down to the "Options" section and click on "Notifications".
5.	Under the "Notifications" section, you will see the option "Automatically watch repositories," click on it.
6.	Here you can select the option "Only direct mentions" which will notify you only when someone directly mentions you or 
unselect it to turn off all notifications.     
7.	After selecting the option, click on the "Save changes" button at the bottom of the page to save your changes.

That's it! You have successfully added a setting to turn off mention notifications on GitHub.

 [https://dolgeneraldgme.com](https://dolgeneraldgme.com/)
