### ISSUE TITLE
how to store articles in local environment.

### ISSUE THREAD

**Issue by Kotarosz727** [laravelio/laravel.io#829]
I hosted laravel.io on Valet.

When trying to store article , error was reported as below.  
I suppose this is due to missing input of TELEGRAM_BOT_TOKEN, and TELEGRAM_CHANNEL in env file.

If so, how can i get it?

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/50207951/154486978-4f5ec65d-53a9-4aaa-bb61-94a963d4645b.png">

Any help would be appreciated, thanks.

**Comment by driesvints** [comment]
We should also add a note in the docs on how to set up Telegram.

**Comment by driesvints** [comment]
We got this merged. You should be able to create articles now and submit them without a notification being sent.
