### ISSUE TITLE
Display article pageviews by using the Fathom API

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#832]
I think it could be cool if we could show the total pageviews an article has received. We could set up a scheduled task that dispatches queued jobs to call the Fathom API to update the counter in the database. The total pageviews are probably gotten from the moment the article was published so we'll need to use the publishing date as a start point.

https://usefathom.com/api

Updating this value can be done once or twice a day maybe? Not sure.

In terms of UI an "x times read" can be shown under the title next to the other meta data as well as on the article overview in the page previews somewhere.

This could also be a neat thing to kickstart the user dashboard again at some point which can aggregate the total reads of a user's articles.

**Comment by ash-jc-allen** [comment]
Hey Dries! If no one's started working on this yet, I'd quite like to have a crack at doing it. I could probably work on it over the next week or so :)

**Comment by driesvints** [comment]
Thanks @ash-jc-allen! I thought @joedixon started working on this but not sure...

**Comment by ash-jc-allen** [comment]
If he's already started working on it, that's cool. If not, I'll have a crack

**Comment by joedixon** [comment]
Thanks Ash. I have already started this. I'll put my face on it now.

**Comment by driesvints** [comment]
We're gonna delay this for now.
