### ISSUE TITLE
wrong overflow on "Tag filter" dialog in articles and forum

### ISSUE THREAD

**Issue by XpycT** [laravelio/laravel.io#856]
articles/overview.blade.php#L125
forum/overview.blade.php#L177

need change **overflow-y-scroll** to **overflow-y-hidden** :)

![image](https://user-images.githubusercontent.com/120016/163248641-16bb8b36-22ed-4150-ab11-4c6bd022f5f1.png)

**Comment by driesvints** [comment]
Hey @XpycT, thanks for reporting this. Which browser (and version) are you using?

**Comment by XpycT** [comment]
**OS:** Windows 10 & Ubuntu 20.04.4 LTS 

**Browsers:**
Microsoft Edge 100.0.1185.39
Brave 1.37.113 Chromium: 100.0.4896.88
Google Chrome 100.0.4896.88

And in Firefox 99.0 scroll is transparent as in screenshot
![image](https://user-images.githubusercontent.com/120016/163344016-afe70561-c604-476f-96b4-49dcab8f3c94.png)

**Comment by faissaloux** [comment]
I have made this PR https://github.com/laravelio/laravel.io/pull/691 before fixing this issue but got closed.

I'll work on it

**Comment by driesvints** [comment]
If you can send the PR again I'll try on Windows as well this time. Thanks!

**Comment by faissaloux** [comment]
I have made this PR https://github.com/laravelio/laravel.io/pull/691 before fixing this issue but got closed.

Would you reopen it or I'll push another one!!
