### ISSUE TITLE
Add icons before menu items

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#863]
Add icons for all menu items under the "chat" and "community" dropdowns. Most of these icons can be found in the footer and others can be found through a Blade Icons set. If we need to add extra sets for social icons it's best that we limit ourselves to a single extra set if possible.

<img width="179" alt="Screenshot 2022-04-29 at 11 12 44" src="https://user-images.githubusercontent.com/594614/165916841-78656e01-1766-4d6a-a9bc-3f8dd0d01cad.png">
<img width="262" alt="Screenshot 2022-04-29 at 11 12 41" src="https://user-images.githubusercontent.com/594614/165916847-c141853c-1fe7-4428-a574-b5e79e8777c1.png">

**Comment by aliwesome** [comment]
This issue is better be closed. :) 
 @driesvints @wadakatu
