### ISSUE TITLE
Bug on RSS Feed Page

### ISSUE THREAD

**Issue by alnahian2003** [laravelio/laravel.io#907]
# Hi there 🙋‍♂️
### I was roaming around laravel.io and when I navigated to the [RSS Feed](https://laravel.io/forum/feed) page, this output shows up:
![error](https://user-images.githubusercontent.com/61485238/185324082-c4688770-4699-417e-ad07-3d383693b4ff.png)

#### Is this normal? My common sense says that, it ain't normal at all! Would you mind checking it out, please?

For your convenience, I provided the output on [Laravel.io's Pastebin](https://paste.laravel.io/38ac7ee4-2163-4ae4-a35e-1cab444b0df6)

**Comment by driesvints** [comment]
That's odd because I get the RSS feed output. What browser are you using?

**Comment by alnahian2003** [comment]
Oh, right. I'm using the latest version of Firefox on Windows 10 from Dhaka, Bangladesh

**Comment by alnahian2003** [comment]
![image](https://user-images.githubusercontent.com/61485238/185335258-bab0c0e5-1171-4c72-a54b-b69c2d1210a1.png)
Now when I revisit the page, this is how it looks!


But after refreshing the page couple of time, seems like the same issue shows up again.
![image](https://user-images.githubusercontent.com/61485238/185335516-8e243f6d-8445-4ae7-b207-4164dd428d27.png)

**Comment by driesvints** [comment]
I don't know really. It always shows up correctly for me. Can you read it out through an RSS reader?

**Comment by alnahian2003** [comment]
I ain't got any clue as well, mate!
Let me show you the Inspect Element of the FEED page
![image](https://user-images.githubusercontent.com/61485238/185344595-fed4903a-35be-4983-bb68-1e37dc6da2dd.png)

As you can see, it seems like the RSS Feed XML code somehow get parsed as HTML by the firefox browser somehow. We can see the xml markup in DevTool clearly. I dunno what's the exact reason here. The Feed page looks good in Chrome.

Maybe this ain't a serious issue to worry about, or it really is?

**Comment by driesvints** [comment]
It's odd because I really can't reproduce it in Firefox either. Maybe this is specific to your case and an extension or something is in the way? Anyway, I don't think this is a serious problem or anything. Thanks for reporting though.

<img width="773" alt="Screenshot 2022-08-18 at 10 26 55" src="https://user-images.githubusercontent.com/594614/185348163-ad62e829-f788-43f5-bd4e-510fd4cf1a3a.png">

**Comment by alnahian2003** [comment]
There you go, You're absolutely correct!
So the problem is with the **Adguard Ad Blocking** extension installed on my firefox browser. I disabled this extension temporarily and seems like the issue literally disappeard after refreshing and revisiting the feed page several times.

Although in my **Chrome** browser, the Adguard extension is also installed and enabled. But I don't see any issue there.

I understand, this was a false issue. I wasn't aware of my action and that's why **I cordially apologize** for wasting your time.
