### ISSUE TITLE
You get 2 notifications if you are mentoined on thread where you already replied

### ISSUE THREAD

**Issue by tvbeek** [laravelio/laravel.io#937]
You get 2 notifications if you are mentioned on thread where you already replied.

You get the notification about a new reply and the notification that you are mentioned.

**Comment by sodu-parisev** [comment]
so what notification type has higher priority in this ? what notification a user has to get in this case mention or replay  ?

**Comment by sodu-parisev** [comment]
oh okay, I will fix my initial PR then
