### ISSUE TITLE
Search for users

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#954]
This will be a larger one to tackle. It would be cool if you could search for user profiles as well besides articles and forum threads. 

This would be presented as another section in the search dropdown. Things do get crowded now though so we'd need to see how we present the search result in a manner that it doesn't overtakes too much space.

**Comment by digitlimit** [comment]
@driesvints  I want to work on this enhancement feature

**Comment by digitlimit** [comment]
@driesvints Tabs will certainly make it cleaner. I will go for tabs
