### ISSUE TITLE
Move social icons

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#962]
Move the GitHub and Twitter icon links out of the "community" dropdown and left of the search icons on the top bar.

<img width="248" alt="Screenshot 2023-11-02 at 10 33 33" src="https://github.com/laravelio/laravel.io/assets/594614/0a5fcad9-56be-4616-85ac-8e9f0ca5a06c">

**Comment by krisnaw** [comment]
Okay will be working on this.
@driesvints  can you please assign this issue to me?

**Comment by driesvints** [comment]
Actually, I'm just going to make these open to everyone and make them first come first served 👍
